CREATE TABLE user_telegram (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  bot_token_enc TEXT NOT NULL,
  bot_token_iv VARCHAR(64) NOT NULL,
  bot_token_tag VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
